### ISSUE TITLE
Новый спрайт генератору щитов в icons/obj/machines/shielding.dmi

### ISSUE THREAD

**Issue by SpadesSlick** [Algol12/CEV-Eris#116]
Обьект состоит из двух частей, одна из которых полное безграфонье. Капаситор подключается к основной машине с любой стороны, насколько я вижу, что нужно учесть при создании спрайта.

Требуется сделать спрайт основной машины в нужной проекции, полностью респрайтнув и выбрав другую форму, потому что это огрызок автолата. Плюс коробку капаситора, подключаемую с любых сторон. Можно заранее изобразить на основной машине провода в 4 направления, или нечто такое. Подробнее о механе можно [почитать тут](http://tauceti.ru/wiki/Guide_to_Shield_Generator).

**Comment by Bloodpriest** [comment]
Сделал спрайты, но нужно закодить, чтобы нужные оверлеи накладывались в нужные места:
1. capacitor_connected - оверлеи, которые накладывается на генератор при коннекте капаситоров.
2. n_capacitor_overlay - оверлей, который накладывается на генератор при коннекте капаситора n-направления. Нужно, чтобы он находился ниже всех остальных оверлеев.
