### ISSUE TITLE
Душевые брига

### ISSUE THREAD

**Issue by SpadesSlick** [Algol12/CEV-Eris#13]
Плин запилил в камеры брига душ, который поливает заключенных холодной и горячей водой, а так же перцем. Все это линковалось к конкретному таймеру камеры через айди. [Коммиты к этому лежат тут.](https://bitbucket.org/animusstations/rebay/commits/f50ef48f869a2816f7527416998b11d3867bb090)

Правда, оно юзало зет уровни и находилось на потолке камеры, так что делать это нужно только после того, как будет решен вопрос с ними.

**Comment by PlinHost** [comment]
Требует #15
