### ISSUE TITLE
Z Уровни

### ISSUE THREAD

**Issue by SpadesSlick** [Algol12/CEV-Eris#15]
Они же этажи. Они уже есть на Бее, нужно определить что именно там есть, чего им не хватает, и перенести недостающие куски с Ребея. Конкретные задачи позже будут ~~описаны в комментариях.~~привязаны к [майлстоуну ](https://github.com/Algol12/CEV-Eris/milestone/7)

**Comment by ModernViolence** [comment]
Список нужных сейчас от многоэтажности фич будет тут: #254

**Comment by LethalGhost** [comment]
База перенесена.
