### ISSUE TITLE
Выпил ненужной одежды

### ISSUE THREAD

**Issue by SpadesSlick** [Algol12/CEV-Eris#155]
Тут указаны конкретные dmi файлы, и стейты в них. Всю одежду использующую эти стейты нужно выпилить, включая спрайты предметов и спрайты в руках, из шкафов, с карты, отовсюду. Если речь касалась важных мест, эквип джобки, селект эквип или еще что-то подобное, написать конкретное место в этот исуй, дабы потом не забыть поставить туда что-то еще. Если будут иные условия, они будут указанны отдельно.

**uniform.dmi**

- [x] blackf
- [x] medical_short
- [x] forensicsred
- [x] sl_suit
- [x] officer
- [x] centcom
- [x] hosred_old
- [x] johnny
- [x] green_suit
- [x] teal_suit
- [x] overalls
- [x] tourist
- [x] tactifool (вместо него использовать syndicate у всей одежды)
- [x] mailman
- [x] vice
- [x] scratch
- [x] redcoat
- [x] really_black_suit
- [x] black_suit_fem
- [x] hosblueclothes
- [x] hosdnavyclothes
- [x] hostanclothes
- [x] officerblueclothes
- [x] officerdnavyclothes
- [x] officertanclothes
- [x] wardenblueclothes
- [x] wardendnavyclothes
- [x] wardentanclothes
- [x] sundress
- [x] jumpsuitdown
- [x] cdc_jumpsuit
- [x] olddressuniform
- [x] retpoluniform
- [x] jeremy_wolf_1
- [x] tian_dress
- [x] bridesmaid
- [x] dress_fire
- [x] dress_orange
- [x] bride_orange
- [x] stripper_g
- [x] stripper_p
- [x] wyatt_uniform
- [x] redshirt2
- [x] captain_fly
- [x] bride_blue
- [x] bride_purple
- [x] bride_red
- [x] dress_cap
- [x] dress_green
- [x] dress_pink
- [x] dress_hop
- [ ] mankini
- [x] plaid_blue
- [x] plaid_purple
- [x] plaid_red
- [ ] dress_rd
- [x] dress_saloon
- [x] dispatch
- [x] nurse
- [x] orderly
- [x] oldman
- [x] huresource
- [x] psysuit
- [x] ana_uniform
- [x] solara_dress
- [x] lilith_uniform
- [x] milohachert
- [x] warden_corporate
- [x] sec_corporate
- [x] hos_corporate
- [x] detective2
- [x] detective_r
- [x] detective2_r
- [x] detective3_r
- [x] mai_yang
- [x] gentlesuit
- [x] rdalt
- [x] swatunder
- [x] sasha
- [x] parker_eliza
- [x] sundress_white
- [x] blacksuit
- [x] black_tango
- [x] charcoal_suit
- [x] navy_suit
- [x] burgundy_suit
- [x] checkered_suit
- [x] tan_suit
- [x] harper_uniform_d
- [x] blackjumpskirt
- [x] scrubsblack
- [x] saaland
- [x] roboticsf

**suit.dmi**

- [x] fire
- [x] rad_old
- [x] syndicate-black
- [x] syndicate-black-green
- [x] syndicate-black-blue
- [x] syndicate-black-med
- [x] syndicate-black-orange
- [x] syndicate-black-red
- [x] syndicate-black-engie
- [x] syndicate-green
- [x] syndicate-green-dark
- [x] syndicate-orange
- [x] syndicate-blue
- [x] rig-old
- [x] thermal
- [x] bombvest
- [x] wizard-fake (использовать вместо него wizard)
- [x] centcom
- [x] oldcaparmor
- [x] labgreen
- [x] suspenders
- [x] captunic
- [x] suitjacket_blue
- [x] suitjacket_blue_open
- [x] holidaypriest
- [x] hastur
- [x] suitjacket_purp
- [x] hgpirate
- [x] justice
- [x] ianshirt
- [x] engspace_suit
- [x] cespace_suit
- [x] overalls
- [x] hosbluejacket
- [x] wardenbluejacket
- [x] wardendnavyjacket
- [x] officertanjacket
- [x] hosdnavyjacket
- [x] hostanjacket
- [x] officerbluejacket
- [x] officerdnavyjacket
- [x] wardentanjacket
- [x] forensics_blue
- [x] forensics_red
- [x] labcoat_burnt
- [x] labcoat_burnt_open
- [x] deus_blueshield
- [x] stripper_g_over
- [x] stripper_p_over
- [x] fr_jacket
- [x] fr_jacket_open
- [x] mantle-unathi
- [x] robe-unathi
- [x] ia_jacket
- [x] ia_jacket_open
- [x] capjacket
- [x] skrell_suit_black
- [x] skrell_suit_white
- [x] red_labcoat_open
- [x] red_labcoat
- [x] purple_labcoat_open
- [x] purple_labcoat
- [x] orange_labcoat_open
- [x] orange_labcoat
- [x] green_labcoat_open
- [x] green_labcoat
- [x] blue_labcoat_open
- [x] blue_labcoat
- [x] br_dress
- [x] ems_jacket_closed
- [x] ems_jacket_open
- [x] zhan_furs
- [x] mitlabcoat
- [x] ertarmor_cmd
- [x] ertarmor_med
- [x] ertarmor_eng
- [x] ertarmor_sec
- [x] leather_jacket
- [x] leather_jacket_nt
- [x] brown_jacket
- [x] brown_jacket_open
- [x] brown_jacket_nt
- [x] brown_jacket_nt_open
- [x] labcoat_cmoalt
- [x] labcoat_cmoalt_open
- [x] s-ninja
- [x] labcoat_black
- [x] labcoat_black_open
- [x] parker_eliza_arms (что это такое, блядь)

В остальных файлах вроде удалять особо ничего нужды нет.

**Comment by EkuDza** [comment]
medical_short - эквип для /datum/job/Paramedic
