### ISSUE TITLE
Переделать, и возможно пересмотреть камеры

### ISSUE THREAD

**Issue by SpadesSlick** [Algol12/CEV-Eris#180]
Серьезно? На Исходе КАЖДОЙ камере был прописан некий индивидуальный тег. Я думал, мы оставили такое говно в 2010 году, это нужно делать автоматически и зонами. Нужно разобраться, как и зачем это происходит, и сделать нормально.

**Comment by SpadesSlick** [comment]
Почти все готово, осталось только заставить работать консоль.

**Comment by LethalGhost** [comment]
Консоль - отдельный Иссуй.
Тэги сделало зонам.
