### ISSUE TITLE
Исправить выдачу доступа офицерам СБ.

### ISSUE THREAD

**Issue by LethalGhost** [Algol12/CEV-Eris#184]
Текущий код не выдает расширенный доступ конкретному офицеру, но расширяет минимальный доступ профессии в целом.

**Comment by SpadesSlick** [comment]
У нас ведь не будет офицеров, закрепленных за отделом.

**Comment by LethalGhost** [comment]
Тогда выпилить?

**Comment by SpadesSlick** [comment]
Да, пожалуй.
