### ISSUE TITLE
Новый HUD

### ISSUE THREAD

**Issue by SpadesSlick** [Algol12/CEV-Eris#192]
Бладприст [нарисовал новый интерфейс](https://cdn.discordapp.com/attachments/154683551365726208/173898421223030786/screen1_display.dmi), по ссылке исходники. Интерфейс должен быть двух типов. Полоской вне экрана дополнительным тайлом (то есть он не налезает на игровое поле, а добавляет новый тайл для себя), такое есть на Ребее. Второй тип - по современной бейской схеме, сверху игрового поля.

Типы интерфейса должны переключаться в сетапе, а так же прямо во время игры через преференсы, специальным вербом.

[Интерфейс полоской(старый) должен выглядеть в игре так.](http://dl1.joxi.net/drive/2016/04/24/0002/1475/181699/99/ac6296ee38.png)
[Интерфейс голографический(новый) должен выглядеть в игре так.](http://dl1.joxi.net/drive/2016/04/23/0002/1475/181699/99/1933d2ccc9.png)

**Comment by EkuDza** [comment]
Текущие "проблемы"
Ксеноморфы не протестированы
Запланировано небольшое изменение кода
Известны баги со слепотой\флешслепотой

**Comment by TheOneForgotten** [comment]
При создании нового тела педальной панелькой худа нету.

**Comment by EkuDza** [comment]
> При создании нового тела педальной панелькой худа не видно.
Временное решение до фикса: вызывать check_HUD.

**Comment by LethalGhost** [comment]
Иссуй заменен новым #276.
