### ISSUE TITLE
Список одежды на респрайт

### ISSUE THREAD

**Issue by SpadesSlick** [Algol12/CEV-Eris#214]
У этого реквеста две части. Первая заключается в респрайте всей одежды на 5 текущих пропорций персонажей, но до того как это будет сделано, необходимо закончить некоторую одежду.

Суть респрайта заключается в следущем. Вся одежда разделена на 5 или 3 файла dmi. Приставка _f означает женские спрайты, _fat толстые, _slim тонкие. Женские спрайты используются в униформе, но не используются в ботинках, например, от чего у одних типов одежды 5 файлов, а у других 3. Жирные спрайты унисексовые, потому что за таким количеством ебучего жира уже нихуя не видно, а значит по полу они не разделяются.

Посмотреть составленные уже куклы можно в humans.dmi, там есть все вариации тел для примерки. По ним нужно сделать вариации **всей** одежды на станции.

На данный момент файлы являются простой копипастой базовой формы мужского и среднего тела. Спрайты внутри нужно просто заменить, не меняя стейты.

**Важно!** Одежда так же имеет еще спрайты в двух местах, в \icons\obj\clothing спрайты предмета одежды, и в \icons\mob\items находятся спрайты одежды в руках. Итемы в руках **не редактировались вообще** и относятся к старым спрайтам одежды, необходимо посмотреть что нужно заменить, и ручками это сделать.

Одежда, которую нужно запилить **до** разделения спрайтов по полу и пропорциям(указаны стейты):
# **uniform.dmi**

**psyche** - просто составить из дефолтной одежды нового вида. Изи.
**atmos** - плохо соотносится с текущей одеждой инженеров (engine), нужно придумать для них нечто похожее, но отличное по виду.
**chiefengineer** - аналогично с атмосом. Может ему жилетку какую придумать, или еще что.
**hop** - тут по сути аналогичное, старый спрайт хопа выглядит не очень на фоне остальных.
# **suit.dmi**

**labcoat_cmo**
**labcoat_cmo_open** - в соответствии с соседними халатами сделать копию, но такую дабы было понятно, что это СМО. Тут не обойтись просто цветными наплечниками, а простой реколор может и не помочь. Посмотришь, в общем.
**ass_jacket** - сам спрайт на персонаже нормальный, а вот спрайт предмета жопный и дешевый. Нужно сделать его лучше, больше.
**bio_security** - переделать в цвета Айронхаммера.

**Comment by LethalGhost** [comment]
@SpadesSlick, закончено?

**Comment by SpadesSlick** [comment]
Да.
