### ISSUE TITLE
Портировать гунский контроллер со свяжего Бея

### ISSUE THREAD

**Issue by SpadesSlick** [Algol12/CEV-Eris#236]
В [этом коммите](https://github.com/Baystation12/Baystation12/commit/de5b1fc66afe9743728cc423eca0a4a30084ab0d) в дев ветку бея был заброшен контроллер гунов, способный размазывать задачи по нескольким тикам, избегая видных игроку лагов. Это крайне критично для нас, ведь мы собираемся нагрузить билд сверху пятиэтажным судном с ебучим гунским светом. Старые контроллеры нас утопят в лагах.

**Comment by ModernViolence** [comment]
Оно даже не в мастере. Не ссыкотно такое в билд впиливать?

**Comment by FinnTheTurtle** [comment]
Как-то не так упомянул, но перенёс в #337
