### ISSUE TITLE
Посмотреть на существующую многоэтажность бэя и понять, что надо сделать

### ISSUE THREAD

**Issue by ModernViolence** [Algol12/CEV-Eris#254]
Возможно, в свежем бэе она допилена?

Список вещей, необходимых для новой карты:
**TODO** (отметить галочками те, что уже есть)

Что пришло в голову:
Лестницы (которые по клику и со ступеньками)
Проводка
Трубы (в том числе спрайты "трубы вниз")
Дыры в полу (проваливание, создание дыр взрывами и рцд)

**Comment by ModernViolence** [comment]
Заассайнил @SpadesSlick, потому что картой сейчас занимаешься ты и тебе виднее, что сейчас для карты нужно.

**Comment by SpadesSlick** [comment]
>Возможно, в свежем бэе она допилена?

Я проверял, они говно кушают, и еще сами толком не знают, что работает их билде от старого кода Луны. По сути, они в таком же положении.

>Лестницы (которые по клику и со ступеньками)
Есть в билде, я не проверял их работу.
Есть еще однотайловые лестницы. Они не работают.
>Дыры в полу (проваливание, создание дыр взрывами и рцд)
Не работает, проваливание в полу возникает только если ходишь по латайсам, где есть шанс провала вниз. Проваливается на правильный этаж, вроде как. Отображение того что внизу не работает. Атмос пока не тестил, но сомневаюсь.
>Проводка
>Трубы (в том числе спрайты "трубы вниз")
Не тестил, но скорее всего не работает.

Наверняка мы что-то упустили при оживлении этого старого кода. Едва ли там нечто фатальное, скорее всего пара важных вещей в коде работает неправильно. В конце концов, есть ребей где все это работало и запускалось, который пусть и устаревшая сборка, но не сильно.

**Comment by PlinHost** [comment]
Мапконфиг завезите

**Comment by LethalGhost** [comment]
Проверить реквест на актуальность.
Вероятно, закрыть.
