### ISSUE TITLE
Определить, что войдет в первый подход респрайта станции и попилить на задачи

### ISSUE THREAD

**Issue by ModernViolence** [Algol12/CEV-Eris#255]

**Comment by SpadesSlick** [comment]
>первый подход

Оно уже года два продолжается, беспрерывно. Сейчас в исуях нет только двух вещей для респрайта, это стены шаттлов и пушки. Но для пушек спрайты уже есть, там нужно будет только править по ходу дела, дорисовывать магазины, спрайты в руках, и прочее. Эти задачи будут возникать в процессе разработки пушек, и писать исуи сейчас для них смысла мало.

А шаттлы я напишу позднее.
