### ISSUE TITLE
Невидимые протезы

### ISSUE THREAD

**Issue by SpadesSlick** [Algol12/CEV-Eris#277]
Докладывали неотображаемость протезов на персонажах. Это был обычный, мужской персонаж, так что это не отсутсвие спрайтов под определенную пропорцию. В прошлом уже возникали подобные баги (#257), лишавшие мартышек ног, и вроде как даже людей еще раньше. Возможно, корень проблемы тот же.

**Comment by LethalGhost** [comment]
Для них нет спрайтов.
Индексы аналогичны таковым у спрайтов обычных тел.
[тэг органа]_[буква пола]_[индекс типа тела]
В текущих наборах пропущена буква пола. Есть ли смысл править пока спрайтов нет, если все равно менять?
