### ISSUE TITLE
Рантаймящее оружие

### ISSUE THREAD

**Issue by SpadesSlick** [Algol12/CEV-Eris#278]
- [x] runtime error: Cannot read null.stored_ammo
proc name: update charge (/obj/item/weapon/gun/projectile/automatic/ironhammer/SMG_sinner/proc/update_charge)
source file: automatic.dm,253

- [x] runtime error: Cannot read null.stored_ammo
proc name: update charge 
(/obj/item/weapon/gun/projectile/ironhammer/judge/proc/update_charge)
source file: pistol.dm,211

- [x] Почти все новое оружие лагает при стрельбе, делая сервер неиграбельным. Как видно из логов, оверлей индикатора заряда не может нормально получить число патронов в магазине.

**Comment by TheOneForgotten** [comment]
Рекурсивная проверка магазинов более не существует.
