### ISSUE TITLE
Риг айронхаммера не имеет спрайтов обьектов под свои части

### ISSUE THREAD

**Issue by SpadesSlick** [Algol12/CEV-Eris#280]
![image](https://cloud.githubusercontent.com/assets/9161564/19625208/0bf4cfde-991b-11e6-8c50-39c2879c4e99.png)
Что-то пошло не так, хотя стейты я указал правильные для спрайтов, по идее.

**Comment by LethalGhost** [comment]
Не нашел ни одного српайта с именем ihs_rig среди спрайтов предметов "на полу".
Вероятно, затерло.
