### ISSUE TITLE
У ИИ и боргов нет доступа к консолям.

### ISSUE THREAD

**Issue by SpadesSlick** [Algol12/CEV-Eris#307]
You need stay face to console.

Нужно выпилить им проверку на это при взаимодействии с консолями. Надо учитывать, что в бее дохрена консолей, модульных и обычных, и проверять нужно не только в одном месте.

**Comment by EkuDza** [comment]
Знаю где косяк, пофикшу

**Comment by EkuDza** [comment]
comment f59fc60f10d87b63e6589b19448a507152264088
