### ISSUE TITLE
Двутайловые двери и их спрайты

### ISSUE THREAD

**Issue by SpadesSlick** [Algol12/CEV-Eris#31]
Впиливание спрайтов двутайловых дверей Ребея, плюс работа над багами, которые были исправлены на Ребее с помощью костыльной виртуальной двери.

Всего нужно сделать три двери, обычную, стеклянную и техтоннельную. Спрайты последней есть в Ребее, но код для нее сделать не успели.

**Comment by bo20202** [comment]
5cebefc
