### ISSUE TITLE
/obj/structure/plasticflaps/mining ломаются при перелете шаттла шахтеров

### ISSUE THREAD

**Issue by SpadesSlick** [Algol12/CEV-Eris#326]
Они начинают пропускать воздух после перелета. Я пока закрою этот костыль стенкой вместо пола в одном месте, но пофиксить все же нужно.

**Comment by Euronem** [comment]
Как вы это сломали.

**Comment by SpadesSlick** [comment]
Никак, Бей просто это не применял. Это было только на шаттле карго у них, но там флапсы всегда обращены в сторону, где есть воздух, что на станции, что на ЦК.

Так что это, скорее всего, было всегда.
