### ISSUE TITLE
Автомат для продажи оружия гражданским за большие цены

### ISSUE THREAD

**Issue by SpadesSlick** [Algol12/CEV-Eris#333]
Требуются спрайты, код и размещения на карту автомата, который продавал бы оружие персоналу. Стоит начать с флешки и перцовки за 800 и 600 соответственно, травматические пистолеты мы добавим чуть позднее, и впишем в автомат сразу, как добавим.

**Comment by LethalGhost** [comment]
@SpadesSlick, Иссуй закрыт?

**Comment by SpadesSlick** [comment]
Травматов нет, значит пусть пока висит.
