### ISSUE TITLE
Зафорсить датчики в третьем режиме

### ISSUE THREAD

**Issue by SpadesSlick** [Algol12/CEV-Eris#344]
Все датчики на всех комбезах, кроме синдикатовских, не оборудованных ими по дефолту, должны быть включены в последний режим. Изменение режима комбезов сделать через кликанье отверткой на сам комбез, ПКМ по костюму же нужно выпилить.

В результате без датчиков будут ходить только преступники и параноики.

**Comment by LethalGhost** [comment]
Если одежду особо не меняли вся одежда профессий имеет дочерние типы для:
/obj/item/clothing/under/rank
Соответственно для выполнения первой части иссуя (согласно пометкам в коде:
```	var/has_sensor = 1 //For the crew computer 2 = unable to change mode
	var/sensor_mode = 0
		/*
		1 = Report living/dead
		2 = Report detailed damages
		3 = Report location
		*/
```)
Установить тут: https://github.com/Algol12/CEV-Eris/blob/master/code/modules/clothing/clothing.dm#L493
Исходные значения has_sensor в двойку и sensor_mode в тройку.
