### ISSUE TITLE
Платина, буква Я

### ISSUE THREAD

**Issue by SpadesSlick** [Algol12/CEV-Eris#46]
Портировать с билда Блю фиксы Я.

**Comment by SpadesSlick** [comment]
Attention! Delta security level reached!
Механизм самоуничтожени&#255; станции был активирован. Весь экипаж должен получить инструкции от глав. Любое сопротивление службе безопасности караетс&#255; смертью. Это не учебнатревога.

**Comment by LethalGhost** [comment]
WIP:

**Comment by LethalGhost** [comment]
Фактически остались отдельные меню. Доработка пойдет в процессе, после обновления.
