### ISSUE TITLE
Новые спрайты оборудованию детектива

### ISSUE THREAD

**Issue by SpadesSlick** [Algol12/CEV-Eris#65]
Сделать новую проекцию для [этого](http://rghost.ru/8qDNf7tSc) оборудования.

**Comment by SpadesSlick** [comment]
Конкретно case, printer, microscope и еще старый спрайт ДНК анализатора переделать под функции нового, и оставить только один.

**Comment by SpadesSlick** [comment]
Пока под вопросом, может быть его вообще выпилим.

**Comment by PlinHost** [comment]
ЛЮМИНОЛ НЕ ТРОГАЙ
ПОРОШОК ТОЖЕ
