### ISSUE TITLE
Блюспесс-гарпун

### ISSUE THREAD

**Issue by SpadesSlick** [Algol12/CEV-Eris#9]
Небольшая фича для РД, запиленная Майншипом. Гарпун имел два режима. В первом он пиздил все что не прикручено на одном тайле, и телепортировал под стрелка. Во втором он телепортировал стрелка на указанный им тайл. Так как это Майншип, следует проверить на адекватность кода. Например, при нажатии на тайл он кидал на случайную точку в зоне. [Запил начался тут.](https://bitbucket.org/animusstations/rebay/commits/42b4718b827cd063296e9f61f5c83d6c3c1620e0)

**Comment by EkuDza** [comment]
Спизден, осталось переделать

**Comment by EkuDza** [comment]
Спизден, осталось переделать
